# Generated by Django 3.2.5 on 2022-08-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField()),
                ('waiting', models.FloatField()),
                ('classification', models.CharField(max_length=30)),
            ],
        ),
    ]
